// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const assert = require('assert');

let options = new chrome.Options();
options.addArguments(
    'headless', 
    'no-sandbox', 
    'disable-dev-shm-usage' 
);

describe('Untitled', function() {
  this.timeout(15000); // Set timeout to 15 seconds

  before(function(done) {
    // Wait for 5 seconds before starting the tests
    setTimeout(done, 5000);
  });

  let driver;
  let vars;
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build();
    vars = {};
  });
  afterEach(async function() {
    await driver.quit();
  });
  it('Untitled', async function() {
    await driver.get("http://localhost:3000/greeting.html");
    await driver.findElement(By.id("nameInput")).click();
    await driver.findElement(By.id("nameInput")).sendKeys("Hans");
    await driver.findElement(By.css("button")).click();
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("greetingMessage"))), 3000);
    assert(await driver.findElement(By.id("greetingMessage")).getText() == "Hello, Hans!");
  });
});