name: Selenium Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Start Selenium Server
      uses: browser-actions/setup-selenium@latest
      with:
        selenium-version: 3.141.59

    - name: Start Chrome Browser
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: latest

    - name: Start server
      run: |
        npm start &
        sleep 5

    - name: Run tests
      run: npm test